[build]
buildCommand = "npm run build --workspace=@snoozeguard/shared && npm run build --workspace=@snoozeguard/api"
installCommand = "npm install --ignore-scripts --no-audit"

[deploy]
startCommand = "npm run start --workspace=@snoozeguard/api"
