[env:sg_alert]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_flags =
  -DCORE_DEBUG_LEVEL=0
lib_deps =
  bblanchon/ArduinoJson@^7.2.1
  knolleary/PubSubClient@^2.8
  dfrobot/DFRobotDFPlayerMini@^1.0.6

[env:sg_sim]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
;debug_tool = custom
build_flags =
  -DCORE_DEBUG_LEVEL=0
  -DNO_BLE
  -DWIFI_SSID=\"Wokwi-GUEST\"
  -DWIFI_PASS=\"\"
  -DWIFI_CHANNEL=6
  -DAPI_HOST=\"host.wokwi.internal\"
lib_deps =
  bblanchon/ArduinoJson@^7.2.1
  knolleary/PubSubClient@^2.8
  dfrobot/DFRobotDFPlayerMini@^1.0.6
